<!--

  __  __           _        _              ____                                      
 |  \/  |         | |      | |            / __ \                                     
 | \  / | __ _  __| | ___  | |__  _   _  | |  | |___  ___ _ __ ___   __ _  __ _  ___ 
 | |\/| |/ _` |/ _` |/ _ \ | '_ \| | | | | |  | / __|/ __| '_ ` _ \ / _` |/ _` |/ _ \
 | |  | | (_| | (_| |  __/ | |_) | |_| | | |__| \__ \ (__| | | | | | (_| | (_| |  __/
 |_|  |_|\__,_|\__,_|\___| |_.__/ \__, |  \____/|___/\___|_| |_| |_|\__,_|\__, |\___|
                                   __/ |                                   __/ |     
                                  |___/                                   |___/      
 -->

<?php 
	get_header();
?>
	<div class="content-container">
<!-- Lite mer kärlek http://nollk.it/love.jpg -->
		<div id="group-points">
			<ul class="list">
				<li>Lag 1: 50</li>
				<li>Lag 2: 50</li>
				<li>Lag 3: 50</li>
				<li>Lag 4: 50</li>
				<li>Lag 5: 50</li>
				<li>Lag 6: 50</li>
			</ul>
		</div>

		<div id="scheme-daily">
			<iframe src="https://www.google.com/calendar/embed?showDate=0&amp;showPrint=0&amp;showTabs=0&amp;showCalendars=0&amp;showTz=0&amp;mode=WEEK&amp;height=600&amp;wkst=2&amp;bgcolor=%23FFFFFF&amp;src=vsslnmoph2ae1se32drhd92psc%40group.calendar.google.com&amp;color=%232F6309&amp;ctz=Europe%2FStockholm"
			 style=" border-width:0 " width="100%" height="400" frameborder="0" scrolling="no"></iframe>
		</div>
		
		<!-- No matter how hard I look, I can't find the bugs ==> http://nollk.it/horv.gif -->

		<div class="posts-container">
			<?php
				query_posts('category_name=startsida&showposts=5');
				if (have_posts()) : 
					while (have_posts()) : the_post(); 
			?>
						<section class="post">
							<article>
								<header class="post-header-container">
									<h2><?php the_title(); ?></h2>
								</header>
								<div class="post-content-container">
									<?php the_content(); ?>
								</div>
								<footer class="post-footer-container">
									<ul class="list">
										<li><?php echo get_the_date(); ?></li>
										<li><?php echo get_the_time(); ?></li>
										<li>Created by: <?php echo get_the_author(); ?></li>
									</ul>
								</footer>
							</article>	
						</section>
			<?php
					endwhile;
				else : 
					echo '<p> No content found </p>' ;
				endif;
			?>
		</div>
		<!--
................................................................................................................................................................
.....................................................................MMMMM......................................................................................
....................................................................8MMMMMM,....................................................................................
....................................................................IMMMMMMM....................................................................................
.....................................................................MMMMMM ...............?MMN. ...............................................................
..................................................................... MMMMZ.............. MMMMMMM...............................................................
..................................................:I  ..............=MMMMMMM=.  ......... MMMMMMM...............................................................
................................................:MMMMM$ ........?MMMMMMMMMMMMMMN7........ 8MMMMMD........ MM7...................................................
................................................MMMMMMM .......,MMMMMMMMMMMMMMMMMM.. :MNMMMMMMMM7.......=MMMMM..................................................
................................................MMMMMMMO ..... MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM7......MMMMMM8 ................................................
......................................MMM ...... NMMMMMM ... ,MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM,.. DMMMMMMM ................................................
....................................8MMMMM .......:MMMMMM:MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM. .MMMMMMMM.................................................
................................... MMMMMMM.........MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM8................................................
...................................MMMMMMMMM.. . ?NMMMMMMMMMMMMMMMMMMMMMMMMMMMMDMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN ...............................................
.................................  MMMMMMMMMMMMN.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM................................................
................................. ZMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM8MMMMMMMMMMMMMMMMMMMMMMMMMMMMM+...............................................
...................................MMMMMMMMMMMMMMMMMMMMMMMMMMMMM..MMMMMMMMMMMMM=  MMMMMMMMMMMMMMMMMMMMMMMMMMMM8M . .............. ..............................
....................................MMMMMMMMMMMMMMMMMMMMMMMMMMMMM.MMMMMMMMMMMM7.. MMMMMMMMMMMMMMMMMMMMMMMMMMMM.MMM= ............. MM............................
................................. +MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM=MMMMMMMMMMMM...MMMMMMMMMMMZ..M=MMMMMMMMMMMM ..NMMMM. ...........7MM.M: .......................
................................ZMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN..MMMMMMMMMMM....,MMMMMMMMMMMM.... MMMMMM   ..... ZMMMMMD .......................
............................. MMMMMMMMMMMMMMMMMMMMMMM8,MMMMMMMMMMMMMMMMMMMMMMMM.MMMMMMMMMMMM....MMMMMMMMMMMM....... MMMMMMM8 ,...MMMMMMM .......................
.........ID ........ ... MMMMMMMMMMM+ MMMMMMMMMMMMMMMMZMMMMMMMMMMMMMMMMMMMMMMMM.MMMMMMMMMMMM...MMMMMMMMMMMM7....... MMMMMMMMMM7. MMMMMMM........................
.......MMMMMM,...  =MMMMMMMMMMMMM:,.....DMMMMMMMMMMMMMM8MMMMMMMMMMMMMMMMMMMMMMM MMMMMMMMMMMM..$MMMMMMMMMMMM...........MMMMMMMMMMMMMMMMM.........................
...... MMMMMMM.  MMMMMMMMMMMMNMM......... NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM. MMMMMMMMMMMMM...........  MMMMMMMMMMMMM   ........................
.......MMMMMMMMMMMMMMMMMMMMM$.............,MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.MMMMMMMMMMMMM..............MMMMMMMMMMMMM ..........................
........MMMMMMMMMMMMMMMMM, ..............  MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM .MMMMMMMMMMMMM ............NMMMMMMMMMMMMMM..........................
...........8MMMMMMMMMMMMMMM ...............:MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.MMMMMMMMMMMMM  ..........,MMMMMMMMMMMMMMMM$.........................
...........8MMMMMMMMMMMMMMMM, ............. MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM,+MMMMMMMMMMMM ...........MMMMMMMMMMMMMMMMMM? ........................
........... MMMMMMMMMMMMMMMMMM.   ..........,MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.MMMMMMMMMMMM7........ .IMMMMMMMMMMMMMMMMMMMM ........................
........... MMMMMMMMMMMMMMMMMMMMMN...........OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMD?MMMMMMMMMMMM....... MMMMMMMMMMMMMMMMMMMMMMMM ........................
...........MMMMMMMMMMMMMMMMMMMMMMMMMM.. ......MMMMMMMMMMMMMMMMMMMMMMMMMMIMMMMMMMMMM$MMMMM.MMMMMMMMMMMM  ....MMMMMMMMMMMMMMMMMMMMMMMMMMM  .......................
...........MMMMMMMMMMMMMMMMMMMMMMMMMMMMM,......MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM,MMMMM.MMMMMMMMMMM . DMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM........................
...........MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM$.....MMMMMMMMMMMMMMMMMMMMMMMMNMMMMMMMMMMMMMMM,MMMMMMMMMMM$MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM: .......................
...........MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMI ..MMMMMMMMMMMMMMMMMMMMMMMM.ZMMMMMMMMMMMMMM MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM .......................
......... .MMMMMM MMMMMMMMMMMMMMMMMMMMMMMMMMMMMN MNMMMMMMMMMMMMMMMMMMMMM..MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM7 .MMMMMMM.......................
...........MMMMMM.. .,MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM..MMMMMMMMMMMMM7MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN  ..  . .MMMMMN .......................
......... .MMMMMM.......  NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM8MMMMMMMMMMMMM..MM,MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM .........  MMM7........................
..........MMMMMM,........   MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM MM.MM.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM, ............MMMM........................
......... MMMMMM...........   MMMMMMMMMMMMMMMMMMMMMMMMMM,MMMMMMMMMMMMD.MM.MM..MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM . ........... .MMM........................
.........  MMMMN............... :MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM. ,MMMMM.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN.................  M= .......................
.......... OMM$.................  ..MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM MMMMMMM8MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN  .................. MM........................
...... .MMMMMN  .................... ...MMMMMNMMMMMMMMMMMMM O.ZMN~    .    ,.ZMMMMMM= MMMMMMMMMMMMMMMMMMMMMMMM+ .......................MMMM~....................
.... . .  .., ...........................  ...  ...    .    ................ .  . ....  ...  .. .    ... .    ........................ .   ..+..................
......................+.........................................................................................................................................
.................... :M.......  MMMMM8  ......................................... 8MI ............................. MM  ...........MM ..........................
.................... MM .........,MMMMMM+.........,N. ............. N,. ......... .MMO............................MMM ...........,MMM ...... D.,................
.................... MM .........,NMMMMMMMO........MMM ............ MMM ............MM ..... MM ...........$MMMMMMMM. .......... NMM   .DMMMMM7 ................
...... MMMM ....... MMM.........MMMMMMMMMMMM  ......MMM .............MMM .......... DMM.....MMM .........MMMMMMMM7.....MMMMMMZZMMMMMMMMMMMMMM, .................
...... MMMMMM ..... MMN.......~MMMMMM=MM$:MMM ......MMM............. MMMM............MMI ..$MMM ......... MMMM.MM  ....MMM.DMMMMMMMMMMN.MMMM. ..................
...... MMMMMMM. ... MM8 .... 7MMMMI.....  7MMM .....MMMM............ DMMM........... MMM ..MMMZ.......... ....MMM..... .MMM .. MMM.....MMM .....................
...... MMMMMMMM ... MMM.... :MMMM. ......  MMMM.... MMMM.............MMMM............MMM .$MMM  ..............MM+........MMM...MMM..  MMZ  .....................
.......MMMMMMMM.....MMM ...,MMMM............MMM.... MMMM ............MMMM........... ?MMN.MMMM ,MMMM.........MMM.........MMM...MMM...MMD .......................
...... ,MMM=MMMM....MMM ...MMMMN........... MMM ... MMM8 ............MMMM.............MMMMMMMMMMMMMM.........MMM........MMM .. MMM.. MM ............'13.........
...... ,MMM. MMMM...MMM ...MMMM............ MMM ...?MMM ............ MMMM............ MMMMMMMM  MMMM.........MMM........  .... MMM.. DMM........................
...... NMMM. .MMM:  MMM7   MMMM ...........MMMM....MMMM ............=MMM ........... ,MMMMMI  ..MMMM.........MMM..............+MMM..  +M........................
...... MMM~...+MMM .MMMM.. MMM7 .......... MMM.....MMMM . .    .....MMMM ...  .    . $MMMM .....MMMM........,MMM..............OMMM .............................
.......MMM.....MMMM =MMM,  MMM$ ..........MMMZ.....MMM.+MMMMMMMMMM..MMMM.MMMMMMMMMM..MMMMO ... :MMM,.........MMM:.............8MMM?.............................
......MMMM .....NMMMMMMMM. MMMM .........MMM8.... MMMMMMMMMMMMMMMM.,MMMMMMMMMMMMMMM. MMMM:.....MMMM ........ MMMM.............7MMMM ............................
....  MMMM. .... IMMMMMMMM..MMMD ......MMMM,..... MMMMMMM..........MMMMMMM?......... MMMM .....MMMM . ... MNMMMMMMM  ..........MMMM.............................
.....OMMMMMN. .... MMMMMMM .MMMMM.. NMMMMM ......DMMMMM  ........ .MMMMM ...........MMMMM......MMMM,NMNMMMMMMMMMMMMMMM.........MMMM ............................
.....MMMMM. ....... ?MMMMM . ,MMMMMMMMMM ....... MMMM ............MMMM  ........... MMMMZ......MMMMMMM.MMMMI. ...  :MMMM,......DMMM ............................
    . MM.           . MMMM.    ,MMMMM            MMM              MMM.              MMMM       NMMMMM.                          MM                        
    
######################################################################################################################################################
#################################################################################################################### #################################
#################################################################################################################### ###########   ###################
###############################################################################################  #################   ########       ##################
####################################################### ########################## #  ##########  ###############   ###########     ##################
########  ############################################# #########################  ### # ########  ######   ####    # ###########     ################
########  ############################################  #######################   ###      ######   #####    ##    #   ######            #############
#########  ###########################################   #######################   ###    ########    ###   ##    ###   ##                ############
#######   #  #################################   #####   ########################        ###########            ######                     #####    ##
######## ## #####   ##################    #####    #    ########## #   ###########        ############         #########                           ###
#######   #######   ##################    ######       #########          ########         ###########         #############           #       #######
#########           ###############        #####        ##########       ##########         ###########        #############           ###############
############            ########             ###        #######          ##########       #   #########       ##############          ################
##############           ###                   ###       ######            ########       #### ########       #############           ################
############ ###            ########        ##           ######             #######         ###  ######        ##########              ###############
#################           ########        #####         ####                 ####          ##########        ########                  #############
###################      ##  #######       #####          ####  #        #########     #      #########         #####        #####        ############
#################        ###   #####        ####         #######          #########    ###      #######         ####     ############      ###########
##############          ###########         ###       ##########            #######   #### #      #####         #####      ########         ##########
############      ##   ###########          ###      ##########              ######         ##### #####         #######     ######         ###########
##########    ######     #########     #     ###   ############     ####      ######     ##  ##########         #########   ####       ###############
######      ############     ####            ################      #######    ##########################        ##########    #   ####################
# ###   ###################  #### ##      #################       #########  ###########################        ##########  ####  ####################
###   #####################  ######  ###################################################################   ##  ##########  #####  ####################
################################### #####################################################################   # ########################################
##########################################################################################################     #######################################
#########################################################################################################  ###  ######################################

...........................................................................,DMMM,. .............................................................................
...................................................   ... .................$MMMMM................  :+. .........................................................
....................................................MMMMM,.................MMMMMMZ............... MMMMZ.........................................................
................................................... MMMMMN ................MMMMMM ...............NMMMMMM...............MMMM7....................................
...................................$MM............. MMMMMM .................DMMM,. .............,MMMMMMM ............ MMMMMM~ ..................................
..............MMMMZ...............MMMMMM........... MMMMMM .................DMMM ................MMMMMMM,............=MMMMMM8.................8MM: .............
..............MMMMM~............. MMMMMM .......... ~MMMM  ................=MMMMMM: ............?MMMMMMMO.............MMMMMM ................MMMMM..............
.............8MMMMMM..............MMMMMM............:MMMMO .............MMMMMMMMMMMMMM  ........ MMMMMMM.............. MMMM.................7MMMMMM ............
............  MMMMMMM.............,MMMM+.........  NMMMMMNM+..........?MMMMMMMMMMMMMMMM:..... NMMMMMMMMMMMMI..........DMMMM................ NMMMMMMM............
............. MMMMMMMM.............MMMM,........MMMMMMMMMMMMMM7 .... .MMMMMMMMMMMMMMMMMMN...MMMMMMMMMMMMMMMMM ......$MMMMMMMMM ............. MMMMMMMI...........
............. MMMMMMMM. .......DMMMMMMMMMMMO...MMMMMMMMMMMMMMMMM....MMMMMMMMMMMMMMMMMMMMMM.MMMMMMMMMMMMMMMMMMM=. IMMMMMMMMMMMMMM$...........?MMMMMMM. ~ ........
............~MMMMMMMMMM ....  MMMMMMMMMMMMMMM MMMMMMMMMMMMMMMMMMM..MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+MMMMMMMMMMMMMMMMM. ...... .MMMMMMMMMM. .........
.........IMMMMMMMMMMMMMMM... MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.8MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.....IMMMMMMMMMMMMMMO.........
........MMMMMMMMMMMMMMMMMM OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+..MMMMMMMMMMMMM ..MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM. .MMMMMMMMMMMMMMMMMM .......
.....,OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM:?MMMMMM..DMMMMMMMMMMMM. MMMMM=MMMMMMMMMMMMMMM NMMMMMMMMMMMMMMMMMMMMM .MMMMMMMMMMMMMMMMMMMM= .....
.... MMMMMMMMMMMMMMMMMMMMMMMMMN=MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM  .MMMMM,. MMMMMMMMMMMZ  MMMMD MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM$MMMMMMMMMMMMMMMMMMMMMMMMMMN ....
....MMMMMMZMMMMMMMMMMMMMDMMMMM.?MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM .MMMMMMM: MMMMMMMMMMM . MMMM, MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM7MMMMMMMMMMMMMMMMMM.....
....MMM=  ?MMMMMMMMMMMMD . MMM.:MMMMMMMMMM,.MMMMMMMMMMMMMMMMMN..MMMMNMMMMMMMMMMMMMMM.DMMMMMN MMMMMMMMMMMMMMMMMMMMM?MMMMMMMMMMMMMMMMMMM.  MMMMMMMMMMMM~..MMM ....
... IMM.. MMMMMMMMMMMMM~..MMMM .MMMMMMMMMM:..MMM MMMMMMMMMMMM$.~MN . ?MMMMMMMMMMMMMMMMMM,MMM ~MMMMMMMMMMMMMM:MMMM. MMMMMMMMMMMMMMMMMMM   MMMMMMMMMMMM, .MM:.....
.....MM8  8MMMMMMMMMMMM..IMMDM,.MMMMMMMMMM,.MMMMDMMMMMMMMMMMM7MMM. ...  NMMMMMMMMMMMMM   NMMMDMMMMMMMMMMMMMMOMMMMM,MMMMMMMMMMMMMMMM.IMM .MMMMMMMMMMMM  MMN .....
....  MM..?MMMMMMMMMMMM.+MM. MMMMMMMMMMMMMMMM=$MMMMMMMMMMMMMMMMM........MMMMMMMMMMMMM+... MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM  7MM,~MMMMMMMMMMM~MMM.......
.......MM.DMMMMMMMMMMMMMMM . ,OMMMMMMMMMMMM8.. .NMMMMMMMMMMMMM.........7MMMMMMMMMMMMM8..... MMMMMMMMMMMMMMMMM..8MMMMMMMMMMMMMMMMMO ...:MMMMMMMMMMMMMMMMM........
.......+MMMMMMMMMMMMMMMMM  ...,NMMMMMMMMMMM.....MMMMMMMMMMMMMMZ ...... MMMMMMMMMMMMMMM........MMMMMMMMMMMMMMM .. .MMMMMMMMMMMMMMM..... . MMMMMMMMMMMM8O ........
........ NMMMMMMMMMMMMMM.... ..MMMMMMMMMMMMM.. +MMMMMMMMMMMMMMM.......,MMMMMMMMMMMMMMM.......MMMMMMMMMMMMMMMM.... .MMMMMMMMMMMMM .......MMMMMMMMMMMMM...........
..........MMMMMMMMMMMMMM:..... MMMMMMMMMMMMM...+MMMMMMMMMMMMMMM .... .MMMMMMMM8NMMMMMM? .....NMMMMMMMMMMMMMMM.....8MMMMMMMMMMMMMM.......MMMMMMMMMMMMMM..........
........,MMMMMMMMMMMMMMMM......MMMMMMMMMMMMM: .MMMMMMMMMMMMMMMMI .....MMMMMMM7.MMMMMMMM ....+MMMMMMMMMMMMMMMM,... MMMMMMMMMMMMMMM. .....MMMMMMMMMMMMMM. ........
........ZMMMMMMMMMMMMMMMM......MMMMMM MMMMMMM  MMMMMMMMMMMMMMMMM......MMMMMMM...+MMMMMM.....MMMMMMMM7IMMMMMMM ....MMMMMMMMMMMMMMM  ....IMMMMMMMMMMMMMM  ........
......... MMMMMMMMMMMMMMM.....:MMMMM7.MMMMMMM .MMMMMMMD MMMMMMMM......MMMMMMN .. MMMMMM ... MMMMMMMM. MMMMMMM:...,MMMMMMM.MMMMMMMM.....MMMMMMM.MMMMMMM  ........
..........MMMMMMMMNMMMMMM ....NMMMMM..MMMMMMM .MMMMMMM..?MMMMMMM ......MMMMM..... MMMMM$ .. MMMMMMM$...MMMMMMM   8MMMMMMN..MMMMMMM ... MMMMMMM..MMMMMM. ........
......... OMMMMMM  MMMMMMM .. NMMMM....IMMMMMDOMMMMMMM...8MMMMMMM ....:MMMMM..... :MMMMM ...MMMMMMM.....MMMMMM, .MMMMMMM....MMMMMM ....MMMMMM=..MMMMMM  ........
..........:MMMMMM..MMMMMMM .. MMMMM ....MMMMMMMMMMMMM ... MMMMMMM~..  MMMMM .......MMMMM$...NMMMMM:.....:MMMMMN..MMMMMM.... =MMMMM? ..7MMMMMM....MMMMMD.........
.......... MMMMM=...MMMMMM . :MMMMI..... MMMMMMMMMMM, .... MMMMMMM... MMMMM ........MMMMM...MMMMMM ......MMMMMM  MMMMMM..... MMMMMM...MMMMMM..... MMMMM.........
...........MMMMM... MMMMMM . :MMMM.......MMMMMMMMMMM.......IMMMMMM ..+MMMMO......... MMMM. ,MMMMM? ......:MMMMM MMMMMM .....  MMMMM . MMMMMM......DMMMM.........
...........MMMMN ....MMMMMM .ZMMMM........MMMMMMMMMO....... MMMMMMN. MMMMM...........MMMM. NMMMMM.........MMMMMMMMMMM$........DMMMMN. MMMMMM......IMMMM. .......
...........MMMM,.....DMMMMM. MMMMM....... MMMMMMMMM......... MMMMMM. MMMMM...........MMMM,.MMMMMM.........MMMMMMMMMMM..........MMMMM NMMMMMM.......MMMMO........
.........  MMMM ......MMMMMD.MMMM  ........MMMMMMMM ........ NMMMMMMMMMMMM...........DMMMMMMMMMMD........  MMMMMMMMMM..........MMMMMNMMMMMMD.......?MMMM........
......... NMMMM.......:MMMMMOMMMM .........MMMMMMMM...........MMMMMMMMMMMM...........7MMMMMMMMMM:..........MMMMMMMMMM..........MMMMMMMMMMMM:........MMMM=.......
.......... MMMM....... MMMMMMMMMM. ........ MMMMMMM ..........DMMMMMMMMMMM .......... MMMMMMMMMM ..........DMMMMMMMM  ......... MMMMMMMMMMM.........MMMMM.......
......... ,MMMM .......MMMMMMMMMM. ..........MMMMM+............ 7IMMMMMMM...........  MMMMMMMMMM.........  +MMMMMMMM............,MMMMMMMMM ......   MMMMM.......
..........NMMM........ :MMMMMMMMM  .........=MMMMM ...............MMMMMMM. ...........,MMMMMMMM.............IMMMMMM~............,MMMMMMMMM ......... MMMM, .....
.........=MMMM=....... IMMMMMM   . ......... MMMM.,...............MMMMM .  ...........  .MMMMM. .............MMMMM= .............  +MMMMI. ..........MMMMMM ....
........ MMMMM,........ MMMMM.  ............+MMMM. .............. OMMM  ................ MMMMM. ............ OMMMM..................MMMM,...........   MMMMM....
........MMMMM. .........MMMM  .............~MMM=   ...............MMMM. .................MMMM7...............IMMMO................. .. .................   .....
...... MMM.............ZMMZ...........  ...,MN .................. :,~...................     ................. . . .............................................
......................... .......................................................................................  ......................................  .....
................................................................................................................................................................
........................................................................................................ ....................................... ...............
................................................................................................................................................................
............................................................ ......... . ..........,........   .................................................................
............................................................ MMMMMMMMMMM, .........MMMMMMMMMMM7.................................................................
........................................................., MMM?........MMM, .... NMMD ...... MMM  ..............................................................
......................................................... MMM. .........MMM ....MMM  .......  MMM:..............................................................
........................................................ MM7.. NMMMMMM.. OMM.. MM8 ..IMMMMMM... MM,.............................................................
.........................................................MM...NMM$$$MM$.. MM...MM. ..MM7$$MMM...MM...... ....................................... ...............
.........................................................MM ..NMM.. MM$.. MM...MM. .,MM.. MMM ..MM..............................................................
.........................................................MM ..NMM...MM$.. MM...MM...:MMMMMMMM...MM..............................................................
.........................................................MM ..NMM...MM$.. MM...MMO...ZNNNNNNN...MM.......................  ...  ................................
.........................................................MM ..NMM...MM$.. MM..  MMM.............MM......................... ....................................
.........................................................MM ..NMM...MM$.. MM.... ZMMMMMMMMMMN...MM..............................................................
.........................................................MM ..NMM...MM$.. MM..... ,.......MMM...MM..............................................................
.........................................................MM ..NMM.. MM$.. MM...MMMMMMMM . MMM...MM..............................................................
.........................................................MM ..NMM   MM$.. MM...MMNND8MM  .MMM...MM..............................................................
.........................................................MM,.. MMMMMMM  .,MM...MMI . MMMMMMM..  MM..............................................................
.........................................................DMMM.. ..... ..MMMN.. ?MMM .   ...  .MMMM..............................................................
........................................................., NMM        .MMM...... MMM..      .MMM:. .............................................................
........................................................... DMMMMMMMMMMMM ....... $MMMMMMMMMMMM  ...............................................................
............................................................ ,         ,...........          . .................................................................
................................................................................................................................................................
-->
	</div>
	
<?php
	get_footer();
?>
